<script>
  import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher();

  export let cell, head

  const notifyUpdate = (e)=> {
		dispatch('update');
  }

  const CLASSNAMES = {left: "text-start", center: "text-center", right: "text-end"}
  $: className = CLASSNAMES[head.align]
</script>

<td class={className}>
  <input class="cell" type="text" on:keyup={notifyUpdate} bind:value={cell.text}>
</td>


<style>
  .cell {
    width: 100%;
    margin: 0;
    border-radius: 0;
    border: 0px solid #ccc;
    padding: 12px
  }

  .cell:hover {
    animation:shadow-inset-center .1s cubic-bezier(.25,.46,.45,.94) both;
  }

  .cell:focus {
    outline:0;
    box-shadow:inset 0 0 3px 0 #aaa
  }

  td {
    padding: 0;
  }

/* ----------------------------------------------
 * Generated by Animista on 2022-8-9 23:38:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  @keyframes shadow-inset-center{
    0%{box-shadow:inset 0 0 0 0 transparent}
    100%{box-shadow:inset 0 0 3px 0 #ccc}}
</style>
