<script>
  import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher();

  export let head
  const notifyUpdate = ()=> {
		dispatch('update');
  }

  const removeColumn = () => {
		dispatch('removeColumn', {
			head: head
		});
  }

  const CLASSNAMES = {left: "text-start", center: "text-center", right: "text-end"}
  $: className = CLASSNAMES[head.align]
</script>

<th class={className}>
  <div class="controls">
    <button class="btn btn-sm btn-danger" on:click={removeColumn}> Remove </button>
    <select class="form-control form-control-sm" on:change={notifyUpdate} bind:value={head.align}>
      <option value="left">left</option>
      <option value="center">center</option>
      <option value="right">right</option>
    </select>
  </div>
  <input class="cell" type="text" on:keyup={notifyUpdate} bind:value={head.text}>
</th>

<style>
  .cell {
    width: 100%;
    margin: 0;
    border-radius: 0;
    border: 0px solid #ccc;
    padding: 12px
  }

  .cell:hover {
    animation:shadow-inset-center .1s cubic-bezier(.25,.46,.45,.94) both;
  }

  .cell:focus {
    outline:0;
    box-shadow:inset 0 0 3px 0 #aaa
  }

  th {
    padding: 0;
    position: relative;
  }

/* ----------------------------------------------
 * Generated by Animista on 2022-8-9 23:38:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  @keyframes shadow-inset-center{
    0%{box-shadow:inset 0 0 0 0 transparent}
    100%{box-shadow:inset 0 0 3px 0 #ccc}}



  .controls {
    position: absolute;
    right: 5px;
    top: -45px;
  }

  .controls .form-control {
    width: auto;
    display: inline;
  }

</style>
